Parameter query and whereClause both specified
Temabit-FOZZY-Group/mirroring pull request #14
Opened 2023-01-05 12:15 UTC by vzubriichuk

Allow to use query + where

2023-01-05 12:36 UTC, hanna-liashchuk requested changes

2023-01-05 12:36 UTC, hanna-liashchuk commented on src/main/scala/palefat/data/mirror/Config.scala
> +    if (_query.isEmpty || (_query.nonEmpty && _whereClause.nonEmpty)) {
this won't work cause if `query` is empty you get true in the first part and the second one is ignored

2023-01-05 12:36 UTC, hanna-liashchuk commented on src/main/scala/palefat/data/mirror/Config.scala
> +    if (_query.isEmpty || (_query.nonEmpty && _whereClause.nonEmpty)) {
I suggest 
  ```
val query: String =
    if (_query.isEmpty) {
      SqlBuilder.buildSelectTableSQL(schema, tab, whereClause.toString)
    } else {
      if (_whereClause.nonEmpty) {
        s"(${_query} where ${whereClause.toString}) as subq"
      } else {
        s"(${_query}) as subq"
      }
    }
```

and no need to modify the method in this case

2023-01-05 13:06 UTC, hanna-liashchuk submitted a review, later dismissed

2023-01-05 13:53 UTC, VShkaberda requested changes
Now it is forbidden to use `where` condition in `query` if `where` argument is given. It should be added to Readme.

2023-01-05 13:53 UTC, VShkaberda commented on src/main/scala/palefat/data/mirror/Config.scala
> +      if (_whereClause.nonEmpty) {
`else if` or make  a new method `SqlBuilder.buildQuerySQL`.

2023-01-09 13:27 UTC, vzubriichuk commented on src/main/scala/palefat/data/mirror/Config.scala
> +    if (_query.isEmpty || (_query.nonEmpty && _whereClause.nonEmpty)) {
Done

2023-01-09 13:51 UTC, VShkaberda approved these changes

2023-01-09 15:02 UTC, hanna-liashchuk approved these changes

2023-01-09 21:56 UTC, merged