Refactoring scalastyle braces
Temabit-FOZZY-Group/mirroring pull request #4
Opened 2022-12-22 14:39 UTC by alexsukhrin

2022-12-22 20:37 UTC, VShkaberda submitted a review, later dismissed

2022-12-23 10:12 UTC, hanna-liashchuk commented
это идет в разрез с `sbt scalafmt`. Либо надо проапдейтить конфиг либо закрывать этот PR

2022-12-23 10:13 UTC, hanna-liashchuk requested changes
это идет в разрез с sbt scalafmt. Либо надо проапдейтить конфиг либо закрывать этот PR

2022-12-23 10:36 UTC, alexsukhrin commented
> это идет в разрез с sbt scalafmt. Либо надо проапдейтить конфиг либо закрывать этот PR

fix scalafmt

2022-12-23 10:39 UTC, hanna-liashchuk approved these changes

2022-12-23 12:39 UTC, VShkaberda approved these changes

2022-12-23 12:58 UTC, merged