refactoring main
Temabit-FOZZY-Group/mirroring pull request #6
Opened 2022-12-26 16:46 UTC by alexsukhrin

2022-12-26 23:06 UTC, VShkaberda requested changes

2022-12-26 23:06 UTC, VShkaberda commented on src/main/scala/palefat/data/mirror/Runner.scala
>      logger.info(
It should be inside `setSparkContext` method. Or returned to `main` and called directly before `setSparkContext`.

2022-12-27 10:33 UTC, alexsukhrin commented on src/main/scala/palefat/data/mirror/Runner.scala
>      logger.info(
it is called before setSparkContext

2022-12-27 14:18 UTC, VShkaberda commented on src/main/scala/palefat/data/mirror/Runner.scala
>      logger.info(
Setting spark context in `setSparkContext` feels much more related to getting/creating spark session unlike `initConfig`. But it looks like spark session is obtained in Config, in `FlowLogger.init`, so this logging message is far from "Creating spark session" either way. It seems better to alter it into
```scala
logger.info(
    s"""Spark session is created with configuration: ${spark.conf.getAll
        .mkString(", ")}"""
    )
```

2022-12-27 16:01 UTC, alexsukhrin commented on src/main/scala/palefat/data/mirror/Runner.scala
>      logger.info(
did not immediately understand you,
moved the logging string to the spark method

2022-12-27 17:39 UTC, VShkaberda approved these changes

2022-12-27 21:12 UTC, hanna-liashchuk approved these changes

2022-12-28 00:10 UTC, merged