bugfix-603429
Temabit-FOZZY-Group/mirroring pull request #68
Opened 2023-06-05 13:45 UTC by VladOrlov

resolves #603429

### Description

Convert datetime2 mssql column to timestamp type instead of string used by default

### Checklist

- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the README.md file

2023-06-06 12:22 UTC, hanna-liashchuk requested changes

2023-06-06 12:22 UTC, hanna-liashchuk commented on src/main/scala/mirroring/services/SparkContextTrait.scala
> +trait SparkContextTrait {
there is a SparkService with the same purpose, one of them should be removed

2023-06-07 12:38 UTC, VladOrlov commented on src/main/scala/mirroring/services/SparkContextTrait.scala
> +trait SparkContextTrait {
SparkService removed

2023-06-07 16:00 UTC, hanna-liashchuk submitted a review, later dismissed

2023-06-12 15:34 UTC, VShkaberda requested changes

2023-06-12 15:34 UTC, VShkaberda commented on src/main/scala/mirroring/Runner.scala
> +    FlowLogger.init(loggerConfig)
Moving `FlowLogger.init` from the line 48 breaks logging. E.g., for missing key now we got:

> [34m2023-06-12 12:01:50.292Z[0m [31merror[0m [[37mConfigBuilder[0m] [31mMissing value for key tab=VS_ct_test7[0m  [34m- (ConfigBuilder.scala:79)[0m
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1 ...

Previous version log example:

> 23/06/12 12:01:30 INFO KubernetesClusterSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.8
> {"timestamp":"23/06/12 12:01:30","level":"ERROR","sparkApplicationId":"spark-e2cd1128e4fc4229b0e4103a4ba7f073","sparkApplicationAttempt":"1","mirrorTaskName":"mirroring_schema__tab","loggerName":"mirroring.builders.ConfigBuilder","message":"Missing value for key tab=VS_ct_test6"}
> 23/06/12 12:01:31 INFO SparkUI: Stopped Spark web UI at http://spark-a36e0888af7b442c-driver-svc.spark-jobs.svc:4040/
> 23/06/12 12:01:31 INFO KubernetesClusterSchedulerBackend: Shutting down all executors
> 23/06/12 12:01:31 INFO KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: Asking each executor to shut down
> 23/06/12 12:01:31 WARN ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed.
> 23/06/12 12:01:32 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
> 23/06/12 12:01:32 INFO MemoryStore: MemoryStore cleared
> 23/06/12 12:01:32 INFO BlockManager: BlockManager stopped
> 23/06/12 12:01:32 INFO BlockManagerMaster: BlockManagerMaster stopped
> 23/06/12 12:01:32 INFO StatsdSink: StatsdSink stopped.
> 23/06/12 12:01:32 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
> 23/06/12 12:01:32 INFO SparkContext: Successfully stopped SparkContext
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1 ...

2023-06-12 15:34 UTC, VShkaberda commented on src/main/scala/mirroring/services/databases/JdbcService.scala
> +    // viz https://jtds.sourceforge.net/typemap.htmlØ
Symbol `Ø` at the end of line.

2023-06-12 15:34 UTC, VShkaberda commented on src/main/scala/mirroring/config/Config.scala
> -  FlowLogger.init(schema, tab, logLvl)
Needed to reinitialize after initializing at the line 48 with dummy params.

2023-06-13 15:19 UTC, VShkaberda approved these changes

2023-06-13 15:22 UTC, hanna-liashchuk approved these changes

2023-06-13 18:41 UTC, merged