612908 type conversion fix
Temabit-FOZZY-Group/mirroring pull request #75
Opened 2023-06-29 06:33 UTC by VladOrlov

resolves #

### Description

### Checklist

- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the README.md file

2023-06-29 15:19 UTC, VShkaberda requested changes
The build isn't working propely:
<details>
  <summary>ParseException</summary>

```
23/06/29 15:15:24 WARN ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed.
Exception in thread "main" org.apache.spark.sql.catalyst.parser.ParseException: 
DataType datetime2 is not supported.(line 1, pos 10)

== SQL ==
datetime2 datetime2
----------^^^

	at org.apache.spark.sql.errors.QueryParsingErrors$.dataTypeUnsupportedError(QueryParsingErrors.scala:239)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.$anonfun$visitPrimitiveDataType$1(AstBuilder.scala:2684)
	at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:157)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitPrimitiveDataType(AstBuilder.scala:2654)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitPrimitiveDataType(AstBuilder.scala:58)
	at org.apache.spark.sql.catalyst.parser.SqlBaseParser$PrimitiveDataTypeContext.accept(SqlBaseParser.java:19187)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.typedVisit(AstBuilder.scala:63)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.$anonfun$visitColType$1(AstBuilder.scala:2760)
	at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:157)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitColType(AstBuilder.scala:2749)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.$anonfun$visitColTypeList$2(AstBuilder.scala:2743)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.$anonfun$visitColTypeList$1(AstBuilder.scala:2743)
	at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:157)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitColTypeList(AstBuilder.scala:2743)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitSingleTableSchema(AstBuilder.scala:107)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.$anonfun$parseTableSchema$1(ParseDriver.scala:77)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:126)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parseTableSchema(ParseDriver.scala:76)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.getCustomSchema(JdbcUtils.scala:825)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:245)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:37)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:350)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:171)
	at mirroring.services.databases.JdbcPartitionedService.loadData(JdbcPartitionedService.scala:83)
	at mirroring.services.MirroringManager.loadDataFromSqlSource(MirroringManager.scala:99)
	at mirroring.services.MirroringManager.startDataMirroring(MirroringManager.scala:39)
	at mirroring.Runner$.main(Runner.scala:32)
	at mirroring.Runner.main(Runner.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

</details>

2023-06-30 11:00 UTC, hanna-liashchuk submitted a review, later dismissed
if CT is ok, lgtm

2023-07-03 15:31 UTC, VShkaberda submitted a review, later dismissed

2023-07-04 06:45 UTC, VShkaberda approved these changes

2023-07-05 08:56 UTC, hanna-liashchuk approved these changes

2023-07-05 09:11 UTC, merged